Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"
    config.ssh.insert_key = true
    config.vm.network "private_network", ip: "172.16.2.51"

    config.vm.provider :virtualbox do |virtualbox|
       virtualbox.name = "centos-client"
       virtualbox.gui = true
       virtualbox.memory = 1024
       virtualbox.cpus = 2
       virtualbox.customize ["modifyvm", :id, "--ioapic", "on"]
       virtualbox.customize ["modifyvm", :id, "--vram", "32"]
    end

end
