Vagrant.configure("2") do |config|

  config.vm.box = "windows_2016_domain_controller_virtualbox"
  config.vm.network "private_network", ip: "172.16.2.50"
  config.vm.hostname = "windows-domain-controller"

  config.vm.provider "virtualbox" do |virtualbox|
     virtualbox.name = "windows-domain-controller"
     virtualbox.gui = true
     virtualbox.memory = 2048
     virtualbox.cpus = 2
  end

end
