# Setting up the domain linuxdc.vagrant with the domain controller

- hosts: domaincontroller
  tasks:

  # ensure the named domain is reachable from the target host;
  # if not, create the domain in a new forest residing on the target host
  - name: Ensure Windows domain exists
    win_domain:
      dns_domain_name: linuxdc.vagrant
      safe_mode_password: password123!
      log_path: c:\ansible_win_domain_controller_create.txt
    register: win_domain_result

  - name: Reboot server if changes were made
    when: win_domain_result.reboot_required
    win_reboot:

  - name: Ensure that the server is a domain controller
    win_domain_controller:
      dns_domain_name: linuxdc.vagrant
      domain_admin_user: chiefadmin@linuxdc.vagrant
      domain_admin_password: password123!
      safe_mode_password: password123!
      state: domain_controller
      log_path: c:\ansible_win_domain_controller.txt
