# Setting up the domain and the domain controller

- hosts: domaincontroller
  tasks:

  # Creates the domain in a new forest if not yet existing
  - name: Ensure Windows domain exists
    win_domain:
      dns_domain_name: '{{ AD_DOMAIN_NAME }}'
      safe_mode_password: '{{ AD_DOMAIN_PASSWORD }}'
      log_path: c:\ansible_win_domain_controller_create.txt
    register: win_domain_result

  - name: Reboot server if changes were made
    when: win_domain_result.reboot_required
    win_reboot:

  - name: Ensure that the server is a domain controller
    win_domain_controller:
      dns_domain_name: '{{ AD_DOMAIN_NAME }}'
      domain_admin_user: '{{ AD_DOMAIN_ADMIN_USER }}@{{ AD_DOMAIN_NAME }}'
      domain_admin_password: '{{ AD_DOMAIN_PASSWORD }}'
      safe_mode_password: '{{ AD_DOMAIN_PASSWORD }}'
      state: domain_controller
      log_path: c:\ansible_win_domain_controller.txt
