# Resetting the linux VMs for a fresh test run

- hosts: ansible-hosts

  tasks:
  - name: Shut down Linux VMs
    shell: cd {{ playbook_dir }}/../{{ item }}; vagrant halt
    with_items:
      - "{{ groups['linux'] }}"

  - name: Destroy Linux VMs
    shell: cd {{ playbook_dir }}/../{{ item }}; vagrant destroy -f
    with_items:
      - "{{ groups['linux'] }}"

  - name: Clean known_hosts
    lineinfile:
      path: ~/.ssh/known_hosts
      state: absent
      regexp: '^172.16.2.5'
