# Starting all VMs for a fresh test run

- hosts: ansible-hosts

  tasks:
  - name: Start VMs
    shell: cd {{ playbook_dir }}/../{{ item }}; vagrant up
    register: start_result
    changed_when: "'Machine booted and ready' in start_result.stdout"
    with_items:
      - "{{ groups['windows'] }}"
      - "{{ groups['linux'] }}"
